using System.Numerics;
using Content.Shared.Crescent.Radar;
using Content.Shared.Shuttles.BUIStates;
using Microsoft.CodeAnalysis;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Physics.Components;
using Content.Client._Crescent.ShipShields; // Rat
using Content.Client._KS14.UI; // KS14
using Robust.Client.UserInterface; // KS14
using Content.Shared._Crescent.HeatSeeking;
using Robust.Shared.Timing;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class NavScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    private SharedTransformSystem _xformSystem;

    private EntityUid? _shuttleEntity;

    public NavScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xformSystem = _entManager.System<SharedTransformSystem>();

        IFFToggle.OnToggled += OnIFFTogglePressed;
        IFFToggle.Pressed = NavRadar.ShowIFF;

        DockToggle.OnToggled += OnDockTogglePressed;
        DockToggle.Pressed = NavRadar.ShowDocks;

        NfInitialize(); // Frontier Initialization for the NavScreen
        HullrotInitialize();

        KsApplyInstrumentLook(); // KS14
    }

    /// <summary>
    ///     KS14: dresses this screen in the instrument look - VT323 face, green CRT palette,
    ///         flat bordered buttons. Cosmetic only: it retitles the two panels and walks the
    ///         side column applying style classes, touching no control's behaviour, name or
    ///         layout. Runtime colour overrides (status readouts that tint themselves) are
    ///         left alone, so anything that already paints itself keeps winning.
    /// </summary>
    private void KsApplyInstrumentLook()
    {
        var palette = KsInstrumentPalette.Nav;

        DisplayPanel.Title = Loc.GetString("shuttle-console-display-label");
        SettingsPanel.Title = Loc.GetString("shuttle-console-nav-settings");

        foreach (var panel in new[] { DisplayPanel, SettingsPanel })
        {
            panel.Accent = palette.Accent;
            panel.Background = palette.Background;
        }

        KsInstrumentDressing.Apply(RightDisplayNav, palette);
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
    }

    private void OnIFFTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFF ^= true;
        args.Button.Pressed = NavRadar.ShowIFF;
    }

    private void OnDockTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowDocks ^= true;
        args.Button.Pressed = NavRadar.ShowDocks;
    }

    public void UpdateState(NavInterfaceState scc)
    {
        NavRadar.UpdateState(scc);
        HullrotUpdateState(scc);
        NfUpdateState(scc); // Frontier Update State
    }

    public void UpdateState(IFFInterfaceState scc)
    {
        NavRadar.UpdateState(scc);
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _shuttleEntity = coordinates?.EntityId;
        NavRadar.SetMatrix(coordinates, angle);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? gridXform) ||
            !_entManager.TryGetComponent(_shuttleEntity, out PhysicsComponent? gridBody))
        {
            MissileLockWarning.Visible = false;
            return;
        }

        var (_, worldRot, worldMatrix) = _xformSystem.GetWorldPositionRotationMatrix(gridXform);
        var worldPos = Vector2.Transform(gridBody.LocalCenter, worldMatrix);

        // Get the positive reduced angle.
        var displayRot = -worldRot.Reduced();

        GridPosition.Text = $"{worldPos.X:0.0}, {worldPos.Y:0.0}";
        GridOrientation.Text = $"{displayRot.Degrees:0.0}";

        var gridVelocity = gridBody.LinearVelocity;
        gridVelocity = displayRot.RotateVec(gridVelocity);
        // Get linear velocity relative to the console entity
        GridLinearVelocity.Text = $"{gridVelocity.X + 10f * float.Epsilon:0.0}, {gridVelocity.Y + 10f * float.Epsilon:0.0}";
        GridAngularVelocity.Text = $"{-gridBody.AngularVelocity + 10f * float.Epsilon:0.0}";

        // Rat-start
        var shield = ShipShieldReadout.Find(_entManager, _shuttleEntity.Value);
        if (shield == null)
        {
            ShieldStatus.Text = Loc.GetString("shuttle-console-shield-absent");
        }
        else if (ShipShieldReadout.IsDown(shield))
        {
            ShieldStatus.Text = Loc.GetString("shuttle-console-shield-recharging",
                ("time", (int) ShipShieldReadout.DownSeconds(shield)));
        }
        else
        {
            // Percent rather than raw damage: hulls run wildly different damage limits, so the
            // absolute number said nothing about how much fight the shield had left in it.
            ShieldStatus.Text = Loc.GetString("shuttle-console-shield-active",
                ("percent", ShipShieldReadout.Percent(shield)));
        }
        // Rat-end

        UpdateMissileLockWarning(_shuttleEntity.Value);

		ShipName.Text = $"{_entManager.GetComponent<MetaDataComponent>(_shuttleEntity.Value).EntityName}";
    }

    /// <summary>
    ///     Crescent: blinks a lock warning on the console while heat seekers are tracking this grid.
    /// </summary>
    private void UpdateMissileLockWarning(EntityUid grid)
    {
        if (!_entManager.TryGetComponent(grid, out MissileLockWarningComponent? warning) || warning.Seekers <= 0)
        {
            MissileLockWarning.Visible = false;
            return;
        }

        MissileLockWarning.Visible = true;
        MissileLockWarning.Text = Loc.GetString("shuttle-console-missile-lock", ("count", warning.Seekers));

        var blinkOn = _timing.RealTime.TotalSeconds % 0.8 < 0.5;
        MissileLockWarning.FontColorOverride = blinkOn ? Color.FromHex("#FF3030") : Color.FromHex("#7A1010");
    }
}
