using System.Linq;
using Content.Shared._Crescent.Contractors.Components;
using Content.Shared._Crescent.Contractors.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Crescent.Contractors.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<PassportSaveMessage>? SaveRequested;

    /// <summary>
    /// Cover prototype ids, indexed the same way as the option button's entries.
    /// </summary>
    private readonly List<string> _covers = new();

    private string _currentCover = string.Empty;

    public PassportWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CoverOption.OnItemSelected += args => CoverOption.SelectId(args.Id);
        SaveButton.OnPressed += OnSavePressed;
    }

    public void UpdateState(PassportBoundUserInterfaceState state)
    {
        PopulateCovers(state.Cover);

        FullNameEdit.Text = state.FullName;
        AgeEdit.Text = state.Age.ToString();
        SpeciesEdit.Text = state.Species;
        SexEdit.Text = state.Sex;
        HeightEdit.Text = state.HeightCm.ToString();
        NationalityEdit.Text = state.Nationality;
        EmployerEdit.Text = state.Employer;
        LifepathEdit.Text = state.Lifepath;
        PassportIdEdit.Text = state.PassportId;
        IssueYearEdit.Text = state.IssueYear.ToString();
        ExpirationYearEdit.Text = state.ExpirationYear.ToString();
    }

    /// <summary>
    /// Lists the bindings a document can be rebound into. The one it currently wears is always
    /// listed even when it is a legacy binding nobody may pick, so the field never lies about
    /// what the reader is holding.
    /// </summary>
    private void PopulateCovers(string current)
    {
        _currentCover = current;

        var covers = _prototype.EnumeratePrototypes<PassportCoverPrototype>()
            .Where(cover => cover.Selectable || cover.ID == current)
            .OrderBy(cover => cover.Priority)
            .ThenBy(cover => cover.ID)
            .ToList();

        _covers.Clear();
        CoverOption.Clear();

        foreach (var cover in covers)
        {
            CoverOption.AddItem(Loc.GetString(cover.NameKey), _covers.Count);
            _covers.Add(cover.ID);
        }

        var index = _covers.IndexOf(current);
        if (index >= 0)
            CoverOption.SelectId(index);
        else if (_covers.Count > 0)
            CoverOption.SelectId(0);
    }

    private void OnSavePressed(BaseButton.ButtonEventArgs args)
    {
        if (!int.TryParse(AgeEdit.Text, out var age)
            || !int.TryParse(HeightEdit.Text, out var heightCm)
            || !int.TryParse(IssueYearEdit.Text, out var issueYear)
            || !int.TryParse(ExpirationYearEdit.Text, out var expirationYear))
        {
            FormStatusLabel.Text = Loc.GetString("passport-ui-number-error");
            return;
        }

        FormStatusLabel.Text = string.Empty;

        var cover = CoverOption.SelectedId >= 0 && CoverOption.SelectedId < _covers.Count
            ? _covers[CoverOption.SelectedId]
            : _currentCover;

        SaveRequested?.Invoke(new PassportSaveMessage(
            cover,
            FullNameEdit.Text,
            age,
            SpeciesEdit.Text,
            SexEdit.Text,
            heightCm,
            NationalityEdit.Text,
            EmployerEdit.Text,
            LifepathEdit.Text,
            PassportIdEdit.Text,
            issueYear,
            expirationYear));
    }
}
