using System.Numerics; // KS14
using Content.Client.Computer;
using Content.Client.PointCannons;
using Content.Client._KS14.UI; // KS14
using Content.Client._Crescent.ShipShields; // KS14: shield readout on the status strip
using Content.Shared.CCVar; // KS14
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.PointCannons;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics; // KS14
using Robust.Client.UserInterface.XAML;
using Content.Client.Shuttles.UI;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Shared.Configuration; // KS14
using Robust.Shared.Timing; // KS14

namespace Content.Client._Crescent.PointCannons;

/// <remarks>
///     KS14: wears the same instrument shell as the shuttle console - flat bezel, VT323 title
///         bar, titled panels, power-on blink. Cosmetic only: every control below keeps its
///         name, its layout slot and its behaviour, and the console still talks to the server
///         through exactly the same three messages.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class TargetingConsoleWindow : KsBaseWindow, IComputerWindow<ShuttleBoundUserInterfaceState> // KS14: instrument shell
{
    /// <summary>KS14: edge width (px) that grabs a resize instead of a move, matching FancyWindow's feel.</summary>
    private const int DragMarginSize = 7;

    [Dependency] private readonly IGameTiming _timing = default!; // KS14
    [Dependency] private readonly IConfigurationManager _cfg = default!; // KS14
    [Dependency] private readonly IEntityManager _entManager = default!; // KS14: shield readout

    /// <summary>KS14: when the shell was created; drives the power-on blink.</summary>
    private TimeSpan _bootStartedAt = TimeSpan.MinValue;

    /// <summary>KS14: the groups the server has selected, for the status strip readout.</summary>
    private List<string> _selectedGroups = new();

    /// <summary>KS14: the group list the rows were last built from, so an unchanged list is left alone.</summary>
    private List<string>? _groups;

    /// <summary>KS14: the group rows by name, so the selection can be lit without rebuilding them.</summary>
    private readonly Dictionary<string, Button> _groupButtons = new();

    /// <summary>KS14: linked cannon count and summed ammo, cached from the last ammo tick.</summary>
    private int _cannonCount;
    private int _ammoValue;
    private int _ammoMax;

    /// <summary>KS14: the hull this console rides, resolved from the nav state, for the shield readout.</summary>
    private EntityUid? _statusGrid;

    public ShuttleNavControl Radar => NavRadar;
    public Action<string>? OnCannonGroupChange;
    public Action? OnServerRefresh;
    public Action<ShipWeaponTargetingMode>? OnTargetingModeChange;

    public TargetingConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        TargetingMode.AddItem(Loc.GetString("ship-weapon-targeting-walls"), (int) ShipWeaponTargetingMode.Walls);
        TargetingMode.AddItem(Loc.GetString("ship-weapon-targeting-tiles-and-walls"), (int) ShipWeaponTargetingMode.TilesAndWalls);
        TargetingMode.OnItemSelected += args => OnTargetingModeChange?.Invoke((ShipWeaponTargetingMode) args.Id);

        KsSetupChrome(); // KS14
        _bootStartedAt = _timing.CurTime; // KS14: power-on blink
    }

    public void UpdateState(TargetingConsoleBoundUserInterfaceState state)
    {
        NavRadar.UpdateState(state.NavState);
        TargetingMode.SelectId((int) state.NavState.WeaponTargetingMode);
        NavRadar.UpdateState(state.IFFState);

        // KS14: the console's own coordinates already ride the nav state, so the strip can find
        // the hull's shield emitter without the server sending anything extra.
        _statusGrid = _entManager.GetCoordinates(state.NavState.Coordinates)?.EntityId;

        if (state.CannonGroups != null)
            UpdateGroupSelector(state.CannonGroups);

        UpdateActiveGroups(state.ActiveGroups); // KS14
    }

    public void UpdateGroupSelector(List<string> groups)
    {
        // KS14: the server pushes this list on every state update, and rebuilding the rows each
        // time threw away their pressed state - and could destroy a row out from under the click
        // that was landing on it. The rows are only rebuilt when the list itself changes.
        if (_groups != null && _groups.SequenceEqual(groups))
            return;

        _groups = new List<string>(groups);
        _groupButtons.Clear();
        CannonGroupSelectorBox.DisposeAllChildren();

        foreach (string groupName in groups)
        {
            Button groupButton = new();
            groupButton.Text = string.Concat(char.ToUpper(groupName[0]), groupName.Substring(1)); //capitalized name
            // KS14: latching, so a selected group stays lit instead of the click vanishing the
            // instant the mouse comes up. Which groups are lit is the server's call - see
            // UpdateActiveGroups - so this only ever shows what the guns are really set to.
            groupButton.ToggleMode = true;
            groupButton.OnPressed += (_) =>
            {
                OnCannonGroupChange?.Invoke(groupName);
            };
            CannonGroupSelectorBox.AddChild(groupButton);
            _groupButtons[groupName] = groupButton; // KS14
        }

        // KS14: the rows are built here rather than in XAML, so they get dressed on the way in.
        KsInstrumentDressing.Apply(CannonGroupSelectorBox, KsInstrumentPalette.Nav);
    }

    /// <summary>
    ///     KS14: lights the groups the server says are selected. Setting <c>Pressed</c> raises no
    ///         press event, so this cannot loop back into another group message - it only corrects
    ///         the row the player just toggled, one state update later.
    /// </summary>
    private void UpdateActiveGroups(List<string> active)
    {
        foreach (var (groupName, button) in _groupButtons)
        {
            button.Pressed = active.Contains(groupName);
        }

        _selectedGroups = active;
        KsRefreshStatusStrip();
    }

    public void UpdateAmmoStatus(List<(int, int)> values)
    {
        // This runs on the UI tick, so reuse the bars instead of rebuilding them every time.
        while (AmmoStatusBox.ChildCount > values.Count)
            AmmoStatusBox.GetChild(AmmoStatusBox.ChildCount - 1).Dispose();

        while (AmmoStatusBox.ChildCount < values.Count)
        {
            var newBar = new AmmoBar();
            newBar.KsMakeInstrument(KsInstrumentPalette.Nav); // KS14
            AmmoStatusBox.AddChild(newBar);
        }

        // KS14: totals for the status strip, summed while the bars are already being walked.
        _cannonCount = values.Count;
        _ammoValue = 0;
        _ammoMax = 0;

        for (var i = 0; i < values.Count; i++)
        {
            var (value, max) = values[i];
            _ammoValue += value; // KS14
            _ammoMax += max; // KS14

            if (AmmoStatusBox.GetChild(i) is not AmmoBar bar)
                continue;

            //funny, but it's important that max value is set before value
            //or it will get clamped to the default max of 100
            bar.MaxValue = max;
            bar.Value = value;
        }

        KsRefreshStatusStrip(); // KS14
    }

    /// <summary>
    ///     KS14: paints the instrument shell. The stock FancyWindow chrome is gone, so the
    ///         bezel, title bar and close button are drawn here from
    ///         <see cref="KsInstrumentChrome"/>. Purely cosmetic - no console behaviour hangs
    ///         off any of it.
    /// </summary>
    private void KsSetupChrome()
    {
        KsInstrumentSheetlet.MakeInstrument(RefreshButton, CloseChromeButton);

        Bezel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = KsInstrumentChrome.WindowBackground,
            BorderColor = KsInstrumentChrome.WindowBorder,
            BorderThickness = new Thickness(2),
        };

        TitleBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = KsInstrumentChrome.TitleBackground,
            BorderColor = KsInstrumentChrome.WindowBorder,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        TitleLabel.FontColorOverride = KsInstrumentChrome.TitleText;

        // The side column sits right next to the plot, so it takes the radar's green cast
        // rather than the amber shell - same split the nav screen already uses.
        var palette = KsInstrumentPalette.Nav;

        FireControlPanel.Title = Loc.GetString("targeting-console-panel-fire-control");
        AmmoPanel.Title = Loc.GetString("targeting-console-panel-ammo");
        GroupPanel.Title = Loc.GetString("targeting-console-panel-groups");

        foreach (var panel in new[] { FireControlPanel, AmmoPanel, GroupPanel })
        {
            panel.Accent = palette.Accent;
            panel.Background = palette.Background;
        }

        StatusStrip.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = KsInstrumentPalette.Shell.Background,
            BorderColor = KsInstrumentPalette.Shell.AccentDim,
            BorderThickness = new Thickness(1),
        };

        KsRefreshStatusStrip();

        CloseChromeButton.OnPressed += _ => Close();
    }

    /// <summary>
    ///     KS14: BaseWindow has no chrome of its own, so the whole surface drags and the
    ///         outer <see cref="DragMarginSize"/> band resizes.
    /// </summary>
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.Move;

        if (!Resizable)
            return mode;

        if (relativeMousePos.Y < DragMarginSize)
            mode = DragMode.Top;
        else if (relativeMousePos.Y > Size.Y - DragMarginSize)
            mode = DragMode.Bottom;

        if (relativeMousePos.X < DragMarginSize)
            mode |= DragMode.Left;
        else if (relativeMousePos.X > Size.X - DragMarginSize)
            mode |= DragMode.Right;

        return mode;
    }

    /// <summary>
    ///     KS14: the power-on flicker, skipped entirely under accessibility.reduced_motion. It
    ///         only modulates the contents grid, so nothing below is aware of it - including the
    ///         radar, which keeps taking clicks throughout.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // KS14: the shield reading moves on its own, so the strip is refreshed per frame rather
        // than only when the ammo or group panels push it.
        KsRefreshStatusStrip();

        if (_bootStartedAt == TimeSpan.MinValue)
            return;

        var since = (_timing.CurTime - _bootStartedAt).TotalSeconds;
        if (since < KsInstrumentAnim.BootDuration && !_cfg.GetCVar(CCVars.ReducedMotion))
        {
            Contents.Modulate = Color.White.WithAlpha(KsInstrumentAnim.BootBrightness(since));
            return;
        }

        Contents.Modulate = Color.White;
        _bootStartedAt = TimeSpan.MinValue;
    }

    /// <summary>
    ///     KS14: the hull's shield strength for the status strip, as a percentage. Percent rather
    ///         than raw damage because damage limits differ wildly between hulls, so the absolute
    ///         number told a gunner nothing about how close the shield was to dropping.
    /// </summary>
    private string KsShieldReadout()
    {
        if (_statusGrid is not { } grid)
            return Loc.GetString("targeting-console-status-shield-none");

        var shield = ShipShieldReadout.Find(_entManager, grid);

        if (shield == null)
            return Loc.GetString("targeting-console-status-shield-none");

        if (ShipShieldReadout.IsDown(shield))
        {
            return Loc.GetString("targeting-console-status-shield-down",
                ("time", (int) ShipShieldReadout.DownSeconds(shield)));
        }

        return Loc.GetString("targeting-console-status-shield-up",
            ("percent", ShipShieldReadout.Percent(shield)));
    }

    /// <summary>
    ///     KS14: the always-on status strip. Nothing on it is new information - it is the ammo
    ///         bars and the group buttons already on screen, totalled - so it costs no extra
    ///         server state and cannot disagree with the panels above it.
    /// </summary>
    private void KsRefreshStatusStrip()
    {
        StatusLabel.Text = Loc.GetString("targeting-console-status",
            ("group", _selectedGroups.Count > 0
                ? string.Join('+', _selectedGroups.Select(g => g.ToUpperInvariant()))
                : Loc.GetString("targeting-console-status-no-group")),
            ("cannons", _cannonCount),
            ("ammo", _ammoValue),
            ("capacity", _ammoMax),
            ("shield", KsShieldReadout()));

        StatusLabel.FontColorOverride = _cannonCount > 0
            ? KsInstrumentPalette.Shell.Text
            : KsInstrumentPalette.Shell.TextDim;

        // Dry only counts when there are guns to be dry: an unlinked console reads 0/0.
        var dry = _cannonCount > 0 && _ammoValue == 0;
        AlertLabel.Visible = dry;
        if (!dry)
            return;

        AlertLabel.Text = Loc.GetString("targeting-console-alert-dry");
        AlertLabel.FontColorOverride = KsInstrumentPalette.Shell.Warning;
    }
}
