using System;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.IntruderTeleporter;
using Content.Shared.Access.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;

namespace Content.Client._Crescent.IntruderTeleporter;

[GenerateTypedNameReferences]
public sealed partial class IntruderTeleporterWindow : FancyWindow
{
    private static readonly Color LeadColor = Color.FromHex("#d4a24c");
    private static readonly Color AlertColor = Color.FromHex("#d13b3b");
    private static readonly Color ReadyColor = Color.FromHex("#4cd47a");

    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly AccessReaderSystem _access;

    public event Action? OnJoinPressed;
    public event Action? OnLaunchPressed;
    public event Action? OnAbortPressed;
    public event Action<EntityCoordinates>? OnTargetPicked;

    private EntityUid _console;

    /// <summary>
    /// The last state the server pushed. Kept so the per-frame countdown redraw has something to count
    /// against without asking the server twice a second for a number it can work out itself.
    /// </summary>
    private IntruderTeleporterBuiState? _state;

    /// <summary>
    /// Whether the local player is carrying the access this console wants. Re-checked on every state push,
    /// since somebody can pick a card up or lose it with the window open.
    /// </summary>
    private bool _hasAccess;

    /// <summary>
    /// Whole seconds left on whichever deadline the orders panel is showing, so the per-frame tick only
    /// rebuilds the readout when the displayed number actually changes. A cooldown runs for minutes.
    /// </summary>
    private int _shownCountdown = -1;

    public IntruderTeleporterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _access = _entManager.System<AccessReaderSystem>();

        // Docks belong to a piloting console, not a boarding one, and the server does not send them.
        RadarScreen.ShowDocks = false;
        RadarScreen.OnRadarClick += coords => OnTargetPicked?.Invoke(coords);

        JoinButton.OnPressed += _ => OnJoinPressed?.Invoke();
        LaunchButton.OnPressed += _ => OnLaunchPressed?.Invoke();
        AbortButton.OnPressed += _ => OnAbortPressed?.Invoke();
    }

    public void SetConsole(EntityUid console)
    {
        _console = console;
    }

    public void UpdateState(IntruderTeleporterBuiState state)
    {
        _state = state;

        RadarScreen.UpdateState(state.Nav);

        _hasAccess = _player.LocalSession?.AttachedEntity is { } player && _access.IsAllowed(player, _console);

        UpdateRoster(state);
        UpdateTarget(state);
        RefreshOrders();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // The countdown and the cooldown are both just deadlines, so the client can run them down itself
        // rather than having the server push state for a number it already knows.
        if (_state is not { } state)
            return;

        // Whichever deadline RefreshOrders would show, so the two agree on what the displayed number is.
        var now = _timing.CurTime;
        var deadline = state.LaunchAt is { } launchAt && launchAt > now ? launchAt : state.CooldownEnd;
        if (deadline is not { } target)
            return;

        if ((int) Math.Ceiling((target - now).TotalSeconds) != _shownCountdown)
            RefreshOrders();
    }

    private void UpdateRoster(IntruderTeleporterBuiState state)
    {
        RosterHeader.Text = Loc.GetString("intruder-teleporter-section-roster-count",
            ("count", state.Squad.Count),
            ("max", state.MaxSquadSize));

        RosterList.RemoveAllChildren();

        var localPlayer = _player.LocalSession?.AttachedEntity;
        var registered = false;

        foreach (var member in state.Squad)
        {
            var uid = _entManager.GetEntity(member.Entity);
            if (uid == localPlayer)
                registered = true;

            var label = new Label
            {
                Text = member.CanCommand
                    ? Loc.GetString("intruder-teleporter-roster-entry-lead", ("name", member.Name))
                    : Loc.GetString("intruder-teleporter-roster-entry", ("name", member.Name)),
                StyleClasses = { "ConsoleText" },
            };

            if (member.CanCommand)
                label.FontColorOverride = LeadColor;

            RosterList.AddChild(label);
        }

        if (state.Squad.Count == 0)
        {
            RosterList.AddChild(new Label
            {
                Text = Loc.GetString("intruder-teleporter-roster-empty-hint"),
                StyleClasses = { "LabelSecondaryColor" },
            });
        }

        JoinButton.Text = Loc.GetString(registered
            ? "intruder-teleporter-leave"
            : "intruder-teleporter-join");

        // Once the order is out the roster is fixed, so signing on or off would only be misleading.
        JoinButton.Disabled = state.LaunchAt != null && !registered;
    }

    private void UpdateTarget(IntruderTeleporterBuiState state)
    {
        if (state.SelectedTargetName == null)
        {
            TargetNameLabel.Text = Loc.GetString("intruder-teleporter-target-none");
            TargetNameLabel.FontColorOverride = null;
            TargetDistanceLabel.Text = string.Empty;
            TargetStatusLabel.Text = Loc.GetString("intruder-teleporter-target-pick-hint", ("range", (int) state.Range));
            TargetStatusLabel.FontColorOverride = null;
            return;
        }

        TargetNameLabel.Text = state.SelectedTargetName;
        TargetDistanceLabel.Text = Loc.GetString("intruder-teleporter-target-distance",
            ("distance", (int) state.SelectedTargetDistance),
            ("range", (int) state.Range));

        var valid = state.SelectedTargetStatus == IntruderTargetStatus.Valid;
        TargetNameLabel.FontColorOverride = valid ? ReadyColor : AlertColor;
        TargetStatusLabel.FontColorOverride = valid ? ReadyColor : AlertColor;
        TargetStatusLabel.Text = Loc.GetString(state.SelectedTargetStatus switch
        {
            IntruderTargetStatus.Valid => "intruder-teleporter-status-valid",
            IntruderTargetStatus.OutOfRange => "intruder-teleporter-status-outofrange",
            IntruderTargetStatus.NotHostile => "intruder-teleporter-status-nothostile",
            IntruderTargetStatus.Lost => "intruder-teleporter-status-lost",
            _ => "intruder-teleporter-status-none",
        });
    }

    private void RefreshOrders()
    {
        if (_state is not { } state)
            return;

        var now = _timing.CurTime;
        var launching = state.LaunchAt is { } launchAt && launchAt > now;

        AbortButton.Visible = launching && _hasAccess;
        AccessHintLabel.Visible = !_hasAccess;
        _shownCountdown = -1;

        if (launching)
        {
            var remaining = Math.Max(0, (int) Math.Ceiling((state.LaunchAt!.Value - now).TotalSeconds));
            _shownCountdown = remaining;
            StatusLabel.Text = Loc.GetString("intruder-teleporter-state-launching",
                ("seconds", remaining),
                ("target", state.LaunchTargetName ?? Loc.GetString("intruder-teleporter-target-none")));
            StatusLabel.FontColorOverride = AlertColor;

            LaunchButton.Disabled = true;
            LaunchButton.Text = Loc.GetString("intruder-teleporter-launch-inflight", ("seconds", remaining));
            return;
        }

        LaunchButton.Text = Loc.GetString("intruder-teleporter-launch");

        if (state.CooldownEnd is { } cooldownEnd && cooldownEnd > now)
        {
            var remaining = (int) Math.Ceiling((cooldownEnd - now).TotalSeconds);
            _shownCountdown = remaining;
            StatusLabel.Text = Loc.GetString("intruder-teleporter-state-cooldown", ("seconds", remaining));
            StatusLabel.FontColorOverride = AlertColor;
            LaunchButton.Disabled = true;
            return;
        }

        if (!_hasAccess)
        {
            StatusLabel.Text = Loc.GetString("intruder-teleporter-state-no-access");
            StatusLabel.FontColorOverride = null;
            LaunchButton.Disabled = true;
            return;
        }

        if (state.Squad.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("intruder-teleporter-state-no-squad");
            StatusLabel.FontColorOverride = null;
            LaunchButton.Disabled = true;
            return;
        }

        if (state.SelectedTargetStatus != IntruderTargetStatus.Valid)
        {
            StatusLabel.Text = Loc.GetString("intruder-teleporter-state-no-target");
            StatusLabel.FontColorOverride = null;
            LaunchButton.Disabled = true;
            return;
        }

        StatusLabel.Text = Loc.GetString("intruder-teleporter-state-ready", ("seconds", (int) state.WarningDelay));
        StatusLabel.FontColorOverride = ReadyColor;
        LaunchButton.Disabled = false;
    }
}
