- type: job
  id: ForemanTFSC
  name: job-name-foreman
  description: job-description-foreman
  playTimeTracker: JobForemanTFSC
  requiredReligion: InfernalExchange
  weight: 2
  startingGear: ForemanGear
  alwaysUseSpawner: true
  whitelisted: true # Rat
  requireAdminNotify: true
  icon: "JobIconSyndieForeman"
  chatNameColor: "#dda52d"
  chatAmplification:
    bubbleScale: 1.09
    shoutBubbleScale: 1.32
    radioScale: 1.23
    radioBold: true
  supervisors: You lead SAW crews and answer to the collective's recognized leadership; follow the Administrator on valid Federation-wide matters.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-foreman
      - type: HullrotFaction
        faction: TFSC
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - Tradeband
        addUnderstood:
          - Freespeak
          - Tradeband
  access:
  - Command
  - Maintenance
  # Shared TFCF gameplay keyring; company access still marks SAW's internal facilities.
  - SyndicateBasic
  - SyndicateGorlex
  - SyndicateInterdyne
  - SyndicateSaws
  - SyndicateRamzi
  - SyndicateCommand # department head
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ForemanGear
  equipment:
    eyes: ClothingEyesHudFactionTFSC
    jumpsuit: ClothingUniformJumpsuitSyndicateSaws
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatHardhatSyndicateForeman
    id: ForemanPDA
    ears: ClothingHeadsetTFSCSawsCommand
    outerClothing: ClothingOuterArmorSyndicateForeman
    belt: ClothingBeltUtilityEngineering
    pocket1: WeaponPistolViperWood
    gloves: ClothingHandsGlovesFingerless
    pocket2: AccessElevatorTFSC
    back: ClothingBackpackTFSCFilledInfanteer
  storage:
    back:
      - RatRubberStampTFSCSAW
