- type: job
  id: IntelligenceOfficerTFSC
  name: job-name-intelligenceofficer
  description: job-description-intelligenceofficer
  playTimeTracker: JobIntelligenceOfficerTFSC
  requiredReligion: InfernalExchange
  ranks:
    RatRankTFSCPatriarchSenior:
    - !type:CharacterPlaytimeRequirement
      tracker: JobIntelligenceOfficerTFSC
      min: 72000 # 20 hours
    RatRankTFSCPatriarchMiddle:
    - !type:CharacterPlaytimeRequirement
      tracker: JobIntelligenceOfficerTFSC
      min: 36000 # 10 hours
    RatRankTFSCPatriarchJunior: []
  weight: 5
  startingGear: IntelligenceOfficerGear
  alwaysUseSpawner: true
  whitelisted: true # Rat
  requireAdminNotify: true
  icon: "JobIconSyndieIntelligenceOfficer"
  chatNameColor: "#839cd7"
  chatAmplification:
    bubbleScale: 1.09
    shoutBubbleScale: 1.32
    radioScale: 1.23
    radioBold: true
  supervisors: You direct Cyberdawn intelligence and answer to its recognized leadership; follow the Administrator on valid Federation-wide matters.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:SexRequirement
      inverted: true
      sex: Female
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: NukeOperative
      - type: HullrotFaction
        faction: TFSC
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - SolCommon
          - Tradeband
          - RobotTalk # one of the main facets of cybersun was AI so they probably understand it
        addUnderstood:
          - Freespeak
          - SolCommon
          - Tradeband
          - RobotTalk
  access:
  - Command
  - Maintenance
  # Shared TFCF gameplay keyring; company access still marks Cyberdawn's internal facilities.
  - SyndicateBasic
  - SyndicateGorlex
  - SyndicateInterdyne
  - SyndicateSaws
  - SyndicateRamzi
  - SyndicateCommand # department head
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: IntelligenceOfficerGear
  equipment:
    eyes: ClothingEyesHudFactionTFSC
    jumpsuit: ClothingUniformJumpsuitSyndicateSuitCyberdawn
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatPatriarch
    id: IntelligenceOfficerPDA
    back: ClothingBackpackTFSCFilledInfanteer
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorCyberdawnPatriarch
    ears: ClothingHeadsetTFSCCyberdawnCommand
    pocket1: AccessElevatorTFSC
    pocket2: RatRubberStampTFSCCyberDawn
