using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{

    public string? BorderColor
    {
        get => Background.ActualModulateSelf.ToHex();

        set => Background.ModulateSelfOverride = Color.FromHex(value, Color.White);
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();

        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();

        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    public PdaWindow()
    {
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    /// <summary>
    /// Sets a custom image behind the PDA content, or restores the default background when null.
    /// </summary>
    public void SetCustomBackground(Texture? texture)
    {
        CustomBackground.Texture = texture;
        CustomBackground.Visible = texture != null;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
