using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.NpcSquad;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.NpcSquad;

[GenerateTypedNameReferences]
public sealed partial class NpcSquadWindow : FancyWindow
{
    /// <summary>
    /// An order for one member, or for everyone when the member is null.
    /// </summary>
    public event Action<NetEntity?, NpcSquadOrder>? OnOrder;

    /// <summary>
    /// Dismiss one member, or everyone when the member is null.
    /// </summary>
    public event Action<NetEntity?>? OnDismiss;

    private static readonly NpcSquadOrder[] Orders =
    [
        NpcSquadOrder.Follow,
        NpcSquadOrder.Defend,
        NpcSquadOrder.Attack,
        NpcSquadOrder.HoldFire,
    ];

    public NpcSquadWindow()
    {
        RobustXamlLoader.Load(this);

        FollowAllButton.OnPressed += _ => OnOrder?.Invoke(null, NpcSquadOrder.Follow);
        DefendAllButton.OnPressed += _ => OnOrder?.Invoke(null, NpcSquadOrder.Defend);
        AttackAllButton.OnPressed += _ => OnOrder?.Invoke(null, NpcSquadOrder.Attack);
        HoldFireAllButton.OnPressed += _ => OnOrder?.Invoke(null, NpcSquadOrder.HoldFire);
        DismissAllButton.OnPressed += _ => OnDismiss?.Invoke(null);
    }

    public void UpdateState(NpcSquadBuiState state)
    {
        CountLabel.Text = Loc.GetString("npc-squad-ui-count", ("count", state.Members.Count), ("max", state.MaxMembers));
        EmptyLabel.Visible = state.Members.Count == 0;
        DismissAllButton.Disabled = state.Members.Count == 0;

        MembersContainer.RemoveAllChildren();

        foreach (var member in state.Members)
        {
            MembersContainer.AddChild(CreateMemberPanel(member));
        }
    }

    private Control CreateMemberPanel(NpcSquadMemberState member)
    {
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1b1b1e"),
                BorderColor = Color.FromHex("#3c3c45"),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            },
        };

        var rows = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 3 };
        panel.AddChild(rows);

        // Name, condition, and whether they are shooting at something right now.
        var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
        header.AddChild(new Label { Text = member.Name, StyleClasses = { StyleNano.StyleClassLabelKeyText }, HorizontalExpand = true, ClipText = true });

        if (member.InCombat)
            header.AddChild(new Label { Text = Loc.GetString("npc-squad-ui-in-combat"), FontColorOverride = Color.FromHex("#e0873a") });

        header.AddChild(new Label
        {
            Text = Loc.GetString($"npc-squad-condition-{member.Condition.ToString().ToLowerInvariant()}"),
            FontColorOverride = ConditionColor(member.Condition),
        });
        rows.AddChild(header);

        // Health bar, ammo, distance, current order.
        var details = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 10 };
        details.AddChild(new ProgressBar
        {
            MinValue = 0f,
            MaxValue = 1f,
            Value = member.Health,
            MinSize = new Vector2(110, 14),
            VerticalAlignment = VAlignment.Center,
            ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = ConditionColor(member.Condition) },
        });

        if (member.SpareMagazines is { } mags)
            details.AddChild(new Label { Text = Loc.GetString("npc-squad-ui-magazines", ("count", mags)) });

        details.AddChild(new Label
        {
            Text = member.Distance is { } distance
                ? Loc.GetString("npc-squad-ui-distance", ("distance", MathF.Round(distance)))
                : Loc.GetString("npc-squad-ui-distance-unknown"),
            StyleClasses = { StyleBase.StyleClassLabelSubText },
        });

        details.AddChild(new Label
        {
            Text = Loc.GetString("npc-squad-ui-current-order", ("order", Loc.GetString($"npc-squad-order-{member.Order.ToString().ToLowerInvariant()}"))),
            HorizontalExpand = true,
            Align = Label.AlignMode.Right,
        });
        rows.AddChild(details);

        // Per-member orders.
        var buttons = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };

        foreach (var order in Orders)
        {
            var button = new Button
            {
                Text = Loc.GetString($"npc-squad-order-{order.ToString().ToLowerInvariant()}"),
                ToggleMode = true,
                Pressed = member.Order == order,
                HorizontalExpand = true,
                StyleClasses = { StyleBase.ButtonSquare },
            };

            var entity = member.Entity;
            button.OnPressed += _ => OnOrder?.Invoke(entity, order);
            buttons.AddChild(button);
        }

        var dismiss = new Button
        {
            Text = Loc.GetString("npc-squad-ui-dismiss"),
            StyleClasses = { StyleBase.ButtonCaution, StyleBase.ButtonSquare },
        };
        var dismissEntity = member.Entity;
        dismiss.OnPressed += _ => OnDismiss?.Invoke(dismissEntity);
        buttons.AddChild(dismiss);

        rows.AddChild(buttons);
        return panel;
    }

    private static Color ConditionColor(NpcSquadMemberCondition condition)
    {
        return condition switch
        {
            NpcSquadMemberCondition.Healthy => Color.FromHex("#5bbf5b"),
            NpcSquadMemberCondition.Wounded => Color.FromHex("#d9c040"),
            NpcSquadMemberCondition.Critical => Color.FromHex("#d94040"),
            _ => Color.FromHex("#777777"),
        };
    }
}
