using System.Linq;
using System.Numerics;
using Content.Client._Crescent.UserInterface;
using Content.Client.Guidebook;
using Content.Client.Humanoid;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.CCVar;
using Content.Shared.Clothing;
using Content.Shared.GameTicking;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Preferences.Loadouts.Effects;
using Content.Shared.Roles;
using Content.Shared.Traits;
using Robust.Shared.GameStates;
using Robust.Shared.ComponentTrees;
using Robust.Client.ComponentTrees;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Direction = Robust.Shared.Maths.Direction;
using Robust.Client.ResourceManagement;
using Content.Client.Resources;
using Content.Shared.Chemistry.Reaction;

namespace Content.Client._Crescent
{
    [GenerateTypedNameReferences]
    public sealed partial class FactionSelectorGui : BoxContainer
    {
        private readonly IClientPreferencesManager _prefsMan;
        private readonly IPrototypeManager _prototypeManager;
        [Dependency] private readonly SpriteSystem _sprite = default!;
        [Dependency] private readonly EntityManager _entities = default!;
        private readonly IResourceCache _resourceCache = default!;
        private CharacterSetupGui gui = default!;
        public HumanoidCharacterProfile? Profile;
        public int? index;

        public event Action<HumanoidCharacterProfile, int >? Save;
        private BoxContainer _factionList => CFactionList;

        /// <summary>
        /// Buttons by faction id, so the screen can show which one the character is already on.
        /// </summary>
        private readonly Dictionary<string, Button> _factionButtons = new();
        private Button? _confirmButton;

        private const string LimitedAvailabilityWarning =
            "WARNING: This faction is only available through midround spawns or specific gamemodes.";

        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            index = slot;
            // The list is built from preferences data, which can arrive after this control was constructed.
            // Rebuilding here also re-highlights whichever faction the character is currently on.
            UpdateUI();
        }

        public FactionSelectorGui(IClientPreferencesManager preferencesManager, IPrototypeManager prototypeManager, CharacterSetupGui setupUI)
        {
            RobustXamlLoader.Load(this);
            _prefsMan = preferencesManager;
            gui = setupUI;
            _prototypeManager = prototypeManager;
            UpdateUI();

        }

        private void SetFaction(FactionPrototype faction)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithFaction(faction.ID);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;
        }
        public void UpdateUI()
        {
            if (!_prefsMan.ServerDataLoaded)
                return;
            // Orphaned, not disposed: saving runs through here from inside the confirm button's own press
            // handler, and disposing a control while it is handling input is asking for trouble.
            _factionList.RemoveAllChildren();
            _factionButtons.Clear();
            FactionInfo.RemoveAllChildren();
            _confirmButton = null;

            var factions = _prototypeManager.EnumeratePrototypes<FactionPrototype>()
                .Where(x => x.Enabled)
                .ToArray();
            // Sorted by weight, then id: prototype enumeration order is not stable between launches, so
            // equal-weight factions would otherwise shuffle around on the player.
            Array.Sort(factions, FactionUIComparer.Instance);

            foreach (var faction in factions)
            {
                var factionButton = new Button();
                // SHORTENED FOR UI's sake
                factionButton.Text = faction.Name;
                factionButton.ToggleMode = true;

                factionButton.ModulateSelfOverride = faction.FactionButtonColor;
                if (faction.LimitedAvailability)
                {
                    factionButton.Text += " *";
                    factionButton.ToolTip = LimitedAvailabilityWarning;
                }

                factionButton.OnPressed += _ =>
                {
                    SelectFaction(faction);
                };
                _factionList.AddChild(factionButton);
                _factionButtons[faction.ID] = factionButton;
            }

            var separator = new PanelContainer();
            separator.ModulateSelfOverride = Color.Black;
            separator.SetHeight = 10f;

            _confirmButton = new Button();
            _confirmButton.Text = "Confirm";
            _confirmButton.SetHeight = 50f;
            _confirmButton.ModulateSelfOverride = Color.Red;
            _confirmButton.OnPressed += _ =>
            {
                SaveCharacter();
            };
            _factionList.AddChild(separator);
            _factionList.AddChild(_confirmButton);

            // Show what the character is already on, if anything. Confirming without a faction used to
            // save an empty one, which just puts the player straight back on this screen.
            var current = Profile?.Faction ?? string.Empty;
            var hasSelection = false;

            if (current != string.Empty
                && _factionButtons.TryGetValue(current, out var currentButton)
                && _prototypeManager.TryIndex<FactionPrototype>(current, out var currentProto))
            {
                currentButton.Pressed = true;
                ShowFactionInfo(currentProto);
                hasSelection = true;
            }

            _confirmButton.Disabled = Profile is null || !hasSelection;
        }

        private void SelectFaction(FactionPrototype faction)
        {
            SetFaction(faction);

            foreach (var (id, button) in _factionButtons)
            {
                button.Pressed = id == faction.ID;
            }

            ShowFactionInfo(faction);

            if (_confirmButton != null)
                _confirmButton.Disabled = Profile is null;
        }

        private void ShowFactionInfo(FactionPrototype faction)
        {
            FactionInfo.RemoveAllChildren();

            // Guard the icon lookup: a missing/typo'd faction icon path throws in Frame0() and would
            // otherwise break the whole character-setup UI from inside this click handler.
            if (faction.Icon != SpriteSpecifier.Invalid)
            {
                try
                {
                    // Eclipsion - fills the info column at the banner's aspect ratio. It used to be pinned at
                    //   1012x189, which is still the ceiling (the banners are 281x53 pixel art, drawn scaled).
                    var factionPhoto = new AspectTextureRect
                    {
                        Texture = faction.Icon.Frame0(),
                        MaxDisplayWidth = 1012f,
                    };
                    FactionInfo.AddChild(factionPhoto);
                }
                catch (Exception e)
                {
                    Logger.ErrorS("lobby", $"Failed to load icon for faction '{faction.ID}': {e}");
                }
            }

            FactionInfo.AddChild(new Label
            {
                Text = faction.DescriptionPrefix,
                FontColorOverride = Color.Red,
                HorizontalAlignment = HAlignment.Center,
                Align = Label.AlignMode.Center,
            });

            if (faction.LimitedAvailability)
            {
                FactionInfo.AddChild(new Label
                {
                    Text = LimitedAvailabilityWarning,
                    FontColorOverride = Color.Gold,
                    HorizontalAlignment = HAlignment.Center,
                    Align = Label.AlignMode.Center,
                });
            }

            // Eclipsion - wraps to the available width. The prototype text is hard-wrapped at ~120 columns,
            //   so fold those breaks back into paragraphs first or it wraps twice.
            var description = new FormattedMessage();
            description.AddText(ReflowParagraphs(faction.Description));
            var descriptionLabel = new RichTextLabel { HorizontalExpand = true };
            descriptionLabel.SetMessage(description);
            FactionInfo.AddChild(descriptionLabel);
        }

        private static string ReflowParagraphs(string text)
        {
            var paragraphs = text.Replace("\r\n", "\n")
                .Split("\n\n", StringSplitOptions.RemoveEmptyEntries)
                .Select(p => string.Join(' ', p.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)));
            return string.Join("\n\n", paragraphs);
        }

        public void SaveCharacter()
        {
            if (Profile is null)
                return;
            if (!_prefsMan.ServerDataLoaded)
                return;
            if (index is null)
                return;
            // Saving an empty faction leaves the character stuck on this screen forever, so refuse it.
            if (string.IsNullOrEmpty(Profile.Faction))
                return;
            Save?.Invoke(Profile, index.Value);
            gui.SwitchToCharacterEditor();
        }

    }
}
