using Content.Client.Shuttles.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.DroneControl;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;
using System.Linq;
using System.Numerics;

namespace Content.Client._Crescent.DroneControl;

[GenerateTypedNameReferences]
public sealed partial class DroneConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    // SharedMapSystem is an entity system, not an IoC service.
    private SharedMapSystem _mapManager => _entity.System<SharedMapSystem>();
    private readonly SharedTransformSystem _xform;

    public ShuttleNavControl Radar => NavRadar;
    public Action<EntityCoordinates>? OnMoveOrder;
    public Action<EntityCoordinates>? OnAttackOrder;

    public Action? OnDeploy;
    public Action<DroneStance>? OnSetStance;
    public Action<DroneTargeting>? OnSetTargeting;
    public Action<DroneFormation>? OnSetFormation;
    public Action<string>? OnSpawn;

    /// <summary>Raised with true to arm a scuttle on the selected drones, false to abort a running one.</summary>
    public Action<bool>? OnSelfDestruct;

    public HashSet<NetEntity> SelectedDrones = new();

    private readonly Dictionary<NetEntity, DroneRow> _droneRows = new();
    private readonly List<DroneSpawnEntry> _spawnableDrones = new();

    // Hull bar colours, worst state wins.
    private static readonly Color HullGood = Color.FromHex("#5EC46B");
    private static readonly Color HullWorn = Color.FromHex("#D4B14A");
    private static readonly Color HullCritical = Color.FromHex("#C74444");

    public DroneConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xform = _entity.System<SharedTransformSystem>();

        NavRadar.OnRadarClick += OnRadarClick;

        SelectAllBtn.OnPressed += _ =>
        {
            foreach (var key in _droneRows.Keys)
                SelectedDrones.Add(key);

            RefreshButtonVisuals();
        };

        DeselectAllBtn.OnPressed += _ =>
        {
            SelectedDrones.Clear();
            RefreshButtonVisuals();
        };

        ScuttleBtn.OnPressed += _ => OnSelfDestruct?.Invoke(true);
        AbortScuttleBtn.OnPressed += _ => OnSelfDestruct?.Invoke(false);

        DeployBtn.OnPressed += _ => OnDeploy?.Invoke();

        StanceAttackBtn.OnPressed += _ => OnSetStance?.Invoke(DroneStance.Attack);
        StanceDefendBtn.OnPressed += _ => OnSetStance?.Invoke(DroneStance.Defend);
        StanceFollowBtn.OnPressed += _ => OnSetStance?.Invoke(DroneStance.Follow);

        TargetEnemiesBtn.OnPressed += _ => OnSetTargeting?.Invoke(DroneTargeting.Enemies);
        TargetAllBtn.OnPressed += _ => OnSetTargeting?.Invoke(DroneTargeting.All);

        foreach (var formation in Enum.GetValues<DroneFormation>())
            FormationOption.AddItem(formation.ToString(), (int) formation);

        FormationOption.OnItemSelected += args =>
        {
            FormationOption.SelectId(args.Id);
            OnSetFormation?.Invoke((DroneFormation) args.Id);
        };

        SpawnOption.OnItemSelected += args => SpawnOption.SelectId(args.Id);

        ProduceBtn.OnPressed += _ =>
        {
            var id = SpawnOption.SelectedId;
            if (id >= 0 && id < _spawnableDrones.Count)
                OnSpawn?.Invoke(_spawnableDrones[id].VesselId);
        };
    }

    private void OnRadarClick(EntityCoordinates coord)
    {
        if (!_timing.IsFirstTimePredicted)
            return;

        var worldCoord = _xform.ToMapCoordinates(coord);
        var mapId = worldCoord.MapId;

        var box = Box2.CenteredAround(worldCoord.Position, new Vector2(2f, 2f));
        EntityUid? foundGrid = null;
        _mapManager.FindGridsIntersecting(mapId, box, (uid, _) =>
        {
            foundGrid = uid;
            return false; // stop when we find one
        }, false, false);

        if (foundGrid != null)
            OnAttackOrder?.Invoke(_xform.ToCoordinates(foundGrid.Value, worldCoord));
        else
            OnMoveOrder?.Invoke(_xform.ToCoordinates(worldCoord));
    }

    public void UpdateState(DroneConsoleBoundUserInterfaceState state)
    {
        NavRadar.UpdateState(state.NavState);
        NavRadar.UpdateState(state.IFFState);

        CarrierPanel.Visible = state.IsCarrier;
        if (state.IsCarrier)
        {
            // Lost drones don't return to the hangar, so the squadron reads short (3/4, 2/4) until a repair
            // station restocks it. Counted in hangar slots, since a heavy drone takes up more than one.
            DeployedLabel.Text = $"Drones: {state.Drones.Count} ({state.AliveCount}/{state.MaxDrones} slots)";

            HangarLabel.Text = state.HangarCount > 0 ? $"Hangar: {state.HangarCount} slots free" : "Hangar empty - no drones left";
            HangarLabel.FontColorOverride = state.HangarCount > 0 ? Color.DarkGray : HullCritical;

            LostLabel.Visible = state.LostCount > 0;
            LostLabel.Text = $"Lost: {state.LostCount} slots - restock at a repair station";
            LostLabel.FontColorOverride = HullWorn;

            TreasuryLabel.Text = state.Treasury is { } treasury ? $"Treasury: {treasury} cr" : string.Empty;
            TreasuryLabel.Visible = state.Treasury != null && state.SpawnableDrones.Count > 0;

            StanceAttackBtn.Pressed = state.Stance == DroneStance.Attack;
            StanceDefendBtn.Pressed = state.Stance == DroneStance.Defend;
            StanceFollowBtn.Pressed = state.Stance == DroneStance.Follow;

            TargetEnemiesBtn.Pressed = state.Targeting == DroneTargeting.Enemies;
            TargetAllBtn.Pressed = state.Targeting == DroneTargeting.All;

            FormationOption.SelectId((int) state.Formation);

            // Rebuild the production dropdown only when the available list or its pricing actually changes.
            if (!_spawnableDrones.SequenceEqual(state.SpawnableDrones))
            {
                var previous = SpawnOption.SelectedId;

                _spawnableDrones.Clear();
                _spawnableDrones.AddRange(state.SpawnableDrones);

                SpawnOption.Clear();
                for (var i = 0; i < _spawnableDrones.Count; i++)
                {
                    var entry = _spawnableDrones[i];
                    var label = entry.HangarCost > 1 ? $"{entry.Name} ({entry.HangarCost} slots)" : entry.Name;
                    if (entry.Price > 0)
                        label = $"{label} - {entry.Price} cr";
                    SpawnOption.AddItem(label, i);
                }

                if (_spawnableDrones.Count > 0)
                    SpawnOption.SelectId(previous >= 0 && previous < _spawnableDrones.Count ? previous : 0);
            }

            SpawnRow.Visible = _spawnableDrones.Count > 0;
        }

        UpdateDroneList(state.Drones);
    }

    private void UpdateDroneList(List<DroneStatusEntry> drones)
    {
        SquadronLabel.Text = drones.Count > 0 ? $"Squadron ({drones.Count})" : "Squadron";
        NoDronesLabel.Visible = drones.Count == 0;

        // Drop selections for drones that no longer exist, so a stale pick can't ride along with a later order.
        SelectedDrones.RemoveWhere(sel => drones.All(d => d.Server != sel));

        // Rebuild rows only when the roster itself changes; otherwise refresh the existing ones in place so
        // the panel doesn't flicker or lose the player's selection every refresh.
        var rosterChanged = drones.Count != _droneRows.Count || drones.Any(d => !_droneRows.ContainsKey(d.Server));
        if (rosterChanged)
        {
            DroneListContainer.DisposeAllChildren();
            _droneRows.Clear();

            foreach (var drone in drones)
            {
                var row = new DroneRow(drone.Server, OnRowToggled);
                _droneRows[drone.Server] = row;
                DroneListContainer.AddChild(row.Root);
            }
        }

        foreach (var drone in drones)
        {
            if (_droneRows.TryGetValue(drone.Server, out var row))
                row.Update(drone, SelectedDrones.Contains(drone.Server));
        }
    }

    private void OnRowToggled(NetEntity drone, bool pressed)
    {
        if (pressed)
            SelectedDrones.Add(drone);
        else
            SelectedDrones.Remove(drone);
    }

    private void RefreshButtonVisuals()
    {
        foreach (var (netEnt, row) in _droneRows)
        {
            row.SetSelected(SelectedDrones.Contains(netEnt));
        }
    }

    private static Color HullColor(float integrity) => integrity switch
    {
        >= 0.75f => HullGood,
        >= 0.4f => HullWorn,
        _ => HullCritical,
    };

    private static string ModeText(DroneStatusEntry drone)
    {
        if (drone.SelfDestructIn is { } seconds)
            return $"SCUTTLING IN {seconds:0}s";

        if (!drone.Powered)
            return "NO POWER";

        return drone.Mode switch
        {
            AutoDroneMode.Launching => "Launching",
            AutoDroneMode.Follow => "In formation",
            AutoDroneMode.Attack => "Engaging",
            AutoDroneMode.Manual => "Manual order",
            AutoDroneMode.SelfDestructing => "Scuttling",
            _ => "Idle",
        };
    }

    private static Color ModeColor(DroneStatusEntry drone)
    {
        if (drone.SelfDestructIn != null || drone.Mode == AutoDroneMode.SelfDestructing)
            return HullCritical;
        if (!drone.Powered)
            return HullCritical;

        return drone.Mode switch
        {
            AutoDroneMode.Attack => HullWorn,
            AutoDroneMode.Idle => Color.DarkGray,
            _ => Color.LightGray,
        };
    }

    /// <summary>
    ///     One drone's row on the status panel: a selection toggle carrying its name, plus a live readout of
    ///     what it is doing and how much hull it has left.
    /// </summary>
    private sealed class DroneRow
    {
        public readonly Control Root;

        private readonly Button _select;
        private readonly Label _status;
        private readonly ProgressBar _hull;
        private readonly StyleBoxFlat _hullStyle;

        public DroneRow(NetEntity drone, Action<NetEntity, bool> onToggled)
        {
            _select = new Button
            {
                ToggleMode = true,
                HorizontalExpand = true,
                ClipText = true,
            };
            _select.OnPressed += _ => onToggled(drone, _select.Pressed);

            _status = new Label
            {
                Margin = new Thickness(4, 0, 0, 0),
            };

            _hullStyle = new StyleBoxFlat { BackgroundColor = HullGood };
            _hull = new ProgressBar
            {
                MinValue = 0f,
                MaxValue = 1f,
                Value = 1f,
                MinHeight = 4,
                Margin = new Thickness(4, 1, 4, 0),
                ForegroundStyleBoxOverride = _hullStyle,
                BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2B2B2B") },
            };

            Root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 0, 0, 4),
                Children = { _select, _status, _hull },
            };
        }

        public void Update(DroneStatusEntry drone, bool selected)
        {
            _select.Text = drone.Name;
            _select.Pressed = selected;

            _status.Text = $"{ModeText(drone)}   Hull {drone.HullIntegrity * 100f:0}%";
            _status.FontColorOverride = ModeColor(drone);

            _hull.Value = Math.Clamp(drone.HullIntegrity, 0f, 1f);
            _hullStyle.BackgroundColor = HullColor(drone.HullIntegrity);
        }

        public void SetSelected(bool selected) => _select.Pressed = selected;
    }
}
