using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Crescent.Lobby;

/// <summary>
/// A scratchpad in the lobby that survives between rounds, reconnects and restarts.
/// The text lives in the client's user data folder only, it is never sent to the server.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyNotesWindow : FancyWindow
{
    [Dependency] private readonly IResourceManager _resource = default!;

    private static readonly ResPath NotesPath = new("/lobby_notes.txt");

    /// Seconds of no typing before the notes are written out, so a keystroke doesn't mean a disk write.
    private const float SaveDelay = 1f;

    private bool _dirty;
    private float _sinceEdit;

    public LobbyNotesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        NotesEdit.Placeholder = new Rope.Leaf(Loc.GetString("lobby-notes-placeholder"));

        if (_resource.UserData.TryReadAllText(NotesPath, out var text))
            NotesEdit.TextRope = new Rope.Leaf(text);

        NotesEdit.OnTextChanged += _ =>
        {
            _dirty = true;
            _sinceEdit = 0f;
            StatusLabel.Text = Loc.GetString("lobby-notes-status-unsaved");
        };

        ClearButton.OnPressed += _ =>
        {
            NotesEdit.TextRope = Rope.Leaf.Empty;
            Save();
        };

        OnClose += Save;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_dirty)
            return;

        _sinceEdit += args.DeltaSeconds;
        if (_sinceEdit >= SaveDelay)
            Save();
    }

    public void Save()
    {
        _dirty = false;

        try
        {
            using var writer = _resource.UserData.OpenWriteText(NotesPath);
            writer.Write(Rope.Collapse(NotesEdit.TextRope));
            StatusLabel.Text = Loc.GetString("lobby-notes-status-saved");
        }
        catch (Exception e)
        {
            Logger.GetSawmill("lobby").Error($"Failed to save lobby notes: {e}");
            StatusLabel.Text = Loc.GetString("lobby-notes-status-failed");
        }
    }
}
